from .prev_music import *
from .next_music import *
from .add_music import *
from .delete_music import *
from .mix_music import *
from .play_music import *
from .pause_music import *
from .stop_music import *
from .on_slider_change import *
